# Site settings
title: Rachael Johnson
email: rj@arenjae.com
description: > # this means to ignore newlines until "baseurl:"
  Find more about the person who will invent an all new Artificial Intelligence
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arenjae.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  earthshine0

# Build settings
markdown: kramdown
